language: node_js
node_js:
  - "node"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "source.zip"
  skip_cleanup: true

before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - cd ../
  - zip -r source.zip .
