language: node_js
node_js:
- node
deploy:
  provider: npm
  email: Nils_Hirsekorn@online.de
  api_key:
    secure: DSPII0KKP9m8mgJlMiupqaVXKa30oQb5EzO4xwXA1GCa2s8GeRuuVWOUYDtuwClstvqhTQ8hvOGuNxBKwhhNisZ0VrPPwdL2fciH4qwet88TGtCdRKiLWiQZJfD1pRGoDeenlOZIwpb6vUUxAjJ8t+HzJJlhrWE+o3WZ91h5Eq8eWV2/dNAYuY9+qwC1gAQSFsO/LBviIuS6AEsUV8OVzvuLIm9U2NaJeKVhmytaCj464L1ftOdxVhsU9kcyawDb84VjzQuc8x1MA0XOU1jroqc/HiyfszWoUdKaxw6TRGvXFhkhxLJeyb5M24yARmboUQoS+H5j/GBxDoHDR3puv8ARcQoPeK7F3Wk9i5gDpB/Bw119Tg+QNicmtGC+pCDFCo9b4AAXGiLIA8Xi3Yd2dpniKnlENWwgN+q5WPS2c2oHraTPBEgZrGOIceYNxfBvQp6WzSsujnlpLzHwGJlX5KwgdbpdzFIwVTYIfDpEnE+yoFc5QSqzXHz+EXaffEl0gSU+bDdzTM3Y0hu1SbvEv9/ZJhevkjF7vFrev1i5FAUP4GZ+fzastLKuXXQwqBHN/HlQFBxkHbBCq/JmJL+iAfzzeWFteZMIZiKpwq2aHsPB6p0LP1UptxJvqM7QNrVVhoEAzdIa5vp0ksemyDeFEO1yFHSHU24a98U5tG5346Q=
  on:
    tags: true
    repo: Kkoile/figure-speaker
