stages:
#- name: "test"
- name: "publish_npm"
  if: branch = master
- name: "create_image"
- name: "publish_image"
  if: branch = master
jobs:
  include:
  - stage: "test"
    language: node_js
    node_js:
    - node
  - stage: "publish_npm"
    before_deploy:
    - npm run build
    deploy:
      provider: npm
      email: Nils_Hirsekorn@online.de
      api_key:
        secure: DSPII0KKP9m8mgJlMiupqaVXKa30oQb5EzO4xwXA1GCa2s8GeRuuVWOUYDtuwClstvqhTQ8hvOGuNxBKwhhNisZ0VrPPwdL2fciH4qwet88TGtCdRKiLWiQZJfD1pRGoDeenlOZIwpb6vUUxAjJ8t+HzJJlhrWE+o3WZ91h5Eq8eWV2/dNAYuY9+qwC1gAQSFsO/LBviIuS6AEsUV8OVzvuLIm9U2NaJeKVhmytaCj464L1ftOdxVhsU9kcyawDb84VjzQuc8x1MA0XOU1jroqc/HiyfszWoUdKaxw6TRGvXFhkhxLJeyb5M24yARmboUQoS+H5j/GBxDoHDR3puv8ARcQoPeK7F3Wk9i5gDpB/Bw119Tg+QNicmtGC+pCDFCo9b4AAXGiLIA8Xi3Yd2dpniKnlENWwgN+q5WPS2c2oHraTPBEgZrGOIceYNxfBvQp6WzSsujnlpLzHwGJlX5KwgdbpdzFIwVTYIfDpEnE+yoFc5QSqzXHz+EXaffEl0gSU+bDdzTM3Y0hu1SbvEv9/ZJhevkjF7vFrev1i5FAUP4GZ+fzastLKuXXQwqBHN/HlQFBxkHbBCq/JmJL+iAfzzeWFteZMIZiKpwq2aHsPB6p0LP1UptxJvqM7QNrVVhoEAzdIa5vp0ksemyDeFEO1yFHSHU24a98U5tG5346Q=
      on:
        tags: true
        repo: Kkoile/figure-speaker
      skip_cleanup: true
  - stage: "create_image"
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - qemu
        - qemu-user-static
        - binfmt-support
        - parted
        - wget
        - dosfstools
        - zip
    script:
    - sudo bash ./create-image
    - xz -z figure-speaker.img -c > figure-speaker.img.xz
    - zip figure-speaker.img.zip figure-speaker.img
  - stage: "publish_image"
    deploy:
      provider: releases
      api_key:
        secure: tqXIU7V0zb2U/oPfPXPFvP4dZw1kKaMtJ1vo+e1EZvXLBtE/UOgMPkgYbHnJCEV1gQbB+owzyDkh4Du1smWiZMuT3iNYWm7OxxzaZwUdNzMCx2WaV7Mx/508jmgAc62EptIf6+qwqPJ0kclGVzzsA91xf/FAlTieyY3t2Ye+XYiKJbXA+6WMakf2YIU1HAHnUFg+NTEPdhBI18pIuLDN7LBrlnLbZ26CM7GZUnyrz+L7nLyB2JUGCR+6+BVOhj2gxmRIkqkNvesg5FBhDaL9vO7TDNfnIOzYRgIZ1hqbt6DlxEn4wYocyrAdyxp2LH0CGPMMQ4hjiLPV1uTHg5aUDDylGW6Ia5jPHQtTBGEhJpvuuNpA9mLmqB2v0BMDutp6h3NO17FFOUagMlR9oq+v/rwWtTcm3/CIkoIQa3HZccjYOAUML89MQW6K0EBfe+vdjMpGJcOV2GkldLSNfAVE39KMRnTXzwPtgtJ3UxpBJHEB494FFQ1WQUGrQ1FgZpaaLN/HxeM0E/WJjkzvY7QsNayzzAkIwkEY6PCk3qqqhWEkd8KyNYNycbDMFENBcjQ8WrbmlTSG/6Q8qV+ZWFkBBnvdOYi4XPNGCVdG+D1SDSGe69PkjIz96mdxBRqzem19Pkyp6RDzUMUEMJRLi/XL3ea6rKfamkN6CN27D/41LNQ=
      file:
      - figure-speaker.img.xz
      - figure-speaker.img.zip
      skip_cleanup: true
      on:
        repo: Kkoile/figure-speaker
        tags: true