#!/bin/bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'

echo "--- Available commands ---"
echo `ls /usr/bin`

echo "--- Start setting up raspberry pi ---"

echo "Setting audio volume to 100% ..."
#TODO
#amixer set PCM -- 100%

echo "Enabling SPI for RFID Reader ..."
echo "dtparam=spi=on" | tee -a /boot/config.txt >/dev/null

echo "Installing Mopidy ..."
wget -q -O - https://apt.mopidy.com/mopidy.gpg | apt-key add -
wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/stretch.list
apt-get update
apt-get install mopidy

echo "Installing Mopidy Spotify Extension ..."
apt-get install mopidy-spotify

echo "Installing Node.js ..."
curl -sL https://deb.nodesource.com/setup_8.x | -E bash -
apt-get install -y nodejs

echo "Configuring NPM ..."
mkdir ~/.npm-global
npm config set prefix /home/pi/.npm-global"

echo "Installing Figure Speaker ..."
npm install -g figure-speaker
mkdir /home/pi/.config/figure-speaker && touch /home/pi/.config/figure-speaker/figures.conf

echo "Create Service File for Figure Speaker ..."
touch /etc/systemd/system/figure-speaker.service
chmod 664 /etc/systemd/system/figure-speaker.service

echo "[Service]" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "WorkingDirectory=/home/pi/" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "ExecStart=/home/pi/.npm-global/bin/figure-speaker" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "Restart=always" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "StandardOutput=syslog" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "StandardError=syslog" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "SyslogIdentifier=figure-speaker" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "User=pi" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "Group=pi" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "Environment=NODE_ENV=production SPOTIFY_CLIENT_ID=<SPOTIFY_CLIENT_ID> SPOTIFY_CLIENT_SECRET=<SPOTIFY_CLIENT_SECRET> GPIO_INCREASE_VOLUME_BUTTON=27 GPIO_DECREASE_VOLUME_BUTTON=22" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "[Install]" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null
echo "WantedBy=multi-user.target" | tee -a /etc/systemd/system/figure-speaker.service >/dev/null

systemctl enable figure-speaker



echo "Installing Figure Speaker Update Manager ..."
npm install -g figure-speaker-update-manager

echo "Create Service File for Figure Speaker Update Manager ..."
touch /etc/systemd/system/figure-speaker-update-manager.service
chmod 664 /etc/systemd/system/figure-speaker-update-manager.service

echo "[Service]" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "WorkingDirectory=/home/pi/" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "ExecStart=/home/pi/.npm-global/bin/figure-speaker-update-manager" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "Restart=always" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "StandardOutput=syslog" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "StandardError=syslog" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "SyslogIdentifier=figure-speaker-update-manager" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "User=pi" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "Group=pi" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "Environment=NODE_ENV=production" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "[Install]" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null
echo "WantedBy=multi-user.target" | tee -a /etc/systemd/system/figure-speaker-update-manager.service >/dev/null

systemctl enable figure-speaker-update-manager


echo "Installing Figure Speaker Wifi Connector ..."
npm install -g figure-speaker-wifi-connector

echo "Create Service File for Figure Speaker Wifi Connector ..."
touch /etc/systemd/system/figure-speaker-wifi-connector.service
chmod 664 /etc/systemd/system/figure-speaker-wifi-connector.service

echo "[Service]" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "WorkingDirectory=/home/pi/" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "ExecStart=/home/pi/.npm-global/bin/figure-speaker-wifi-connector" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "Restart=always" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "StandardOutput=syslog" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "StandardError=syslog" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "SyslogIdentifier=figure-speaker-wifi-connector" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "User=pi" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "Group=pi" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "Environment=NODE_ENV=production" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "[Install]" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null
echo "WantedBy=multi-user.target" | tee -a /etc/systemd/system/figure-speaker-wifi-connector.service >/dev/null

systemctl enable figure-speaker-wifi-connector
